from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.units import inch
import os

class StudyPlanPDFGenerator:
    def __init__(self, output_dir="static/pdfs"):
        self.output_dir = output_dir
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

    def generate_plan_pdf(self, exam_name, plan_text, filename):
        file_path = os.path.join(self.output_dir, filename)
        doc = SimpleDocTemplate(file_path, pagesize=letter)
        styles = getSampleStyleSheet()
        
        # Build Elements
        elements = []
        
        # Title
        title_style = styles['Title']
        elements.append(Paragraph("Raksha AI Study Plan", title_style))
        elements.append(Spacer(1, 0.2 * inch))
        
        # Exam Name
        header_style = styles['Heading2']
        elements.append(Paragraph(f"Exam: {exam_name}", header_style))
        elements.append(Spacer(1, 0.2 * inch))
        
        # Body Content
        body_style = styles['Normal']
        # Replace newlines with <br/> for Paragraph compatibility
        formatted_text = plan_text.replace('\n', '<br/>')
        elements.append(Paragraph(formatted_text, body_style))
        
        # Footer
        elements.append(Spacer(1, 1 * inch))
        elements.append(Paragraph("Generated by Raksha AI Bot - Empowering Safely through Education.", styles['Italic']))
        
        doc.build(elements)
        return file_path
